development:
  adapter: async

test:
  adapter: async

# Exercise 6.13 : ActionCable
production:
  # adapter: postgresql
  # url: <%= ENV["DATABASE_URL"] %>
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  # url: redis://localhost:6379/1
  # channel_prefix: rails_app_1_production
